import re
import sys
import os

def translate_c_to_vh(input_file, output_file):
    if not os.path.exists(input_file):
        print(f"Error: {input_file} not found!")
        return

    with open(input_file, 'r') as f:
        lines = f.readlines()

    with open(output_file, 'w') as f:
        f.write("// ************************************************************\n")
        f.write("// Automatically generated by gen_vh.py from autoconf.h\n")
        f.write("// DO NOT EDIT BY HAND\n")
        f.write("// ************************************************************\n\n")

        for line in lines:
            # 只匹配 #define V_CONFIG_xxxx 这种格式
            # 如果你想也包含普通的 CONFIG_，只需将 V_CONFIG 改为 CONFIG
            match = re.match(r'#define\s+(CONFIG_V_\w+)\s+(.*)', line)
            
            if match:
                macro_name = match.group(1)
                macro_value = match.group(2).strip()
                new_name = macro_name.replace("CONFIG_V_", "CONFIG_")

                # 转换十六进制: 0xa0000 -> 32'ha0000
                if macro_value.startswith('0x'):
                    hex_val = macro_value[2:]
                    processed_value = f"32'h{hex_val}"
                # 如果是布尔值 1，Verilog 中通常直接定义即可，或者保持为 1
                else:
                    processed_value = macro_value

                f.write(f"`define {new_name} {processed_value}\n")

    print(f"Success: {output_file} generated.")
if __name__ == "__main__":
    # 如果有参数传入，使用参数；否则使用默认值
    input_path = sys.argv[1] if len(sys.argv) > 1 else 'autoconf.h'
    output_path = sys.argv[2] if len(sys.argv) > 2 else 'soc_config.vh'
    translate_c_to_vh(input_path, output_path)
